sub main()
    channel = {uuid: "abc-123", name: "Example TV"}
    content = livePlaybackDescriptor("http://tv.example.test:9191/base/", channel)
    assertEqual(content.url, "http://tv.example.test:9191/base/proxy/ts/stream/abc-123?output_format=mpegts", "use existing continuous TS output")
    assertEqual(content.streamFormat, "ts", "use Roku accepted TS enum instead of invalid mpegts hint")
    assertEqual(content.programId, "abc-123", "stable media diagnostic identity")
    assertEqual(content.live, true, "live UI metadata")
    assertEqual(content.doesExist("httpHeaders"), false, "credentials are configured separately")
    assertEqual(livePlaybackDescriptor("https://", channel), invalid, "reject invalid server")
    assertEqual(livePlaybackDescriptor("http://tv.test", {uuid: "bad?key=secret", name: "Bad"}), invalid, "reject malformed stream identifier")
    assertEqual(livePlaybackDescriptor("http://tv.test", invalid), invalid, "reject missing channel")
    assertEqual(sanitizePlaybackDiagnostic("Failed https://host.test/user/password/live.ts?token=secret at reader"), "Failed [media URL] at reader", "redact credential-bearing media URL")
    assertEqual(sanitizePlaybackDiagnostic("Key secret failed", "secret"), "Key [credential] failed", "redact API key")
    assertEqual(sanitizePlaybackDiagnostic("Authorization: ApiKey secret"), "[credential header]", "redact credential header")
    assertEqual(sanitizePlaybackDiagnostic("error at /movie/viewer/test-only/21.mp4"), "error at [media path]", "redact credential-bearing relative Xtream path")
    assertEqual(sanitizePlaybackDiagnostic("password=test-only&username=viewer"), "[credential]&[credential]", "redact credential-bearing query fragments")
    message = playbackFailureText(-1, "reader pick stream error:HTTP error:Full-content response on a range request:200")
    assertEqual(instr(1, message, "byte-range") > 0, true, "explain measured HTTP failure")
    assertEqual(instr(1, playbackFailureText(-5, ""), "media playback error") > 0, true, "generic media error is not proof of unsupported codec")
    stalled = playbackFailureText(-5, "buffering is stalled:extra:err_clip_idx:0")
    assertEqual(instr(1, stalled, "stalled while buffering") > 0, true, "report native buffering stall accurately")
    assertEqual(instr(1, stalled, "could not decode"), 0, "stall is not an unsupported codec claim")
    assertEqual(isStartupBufferingStall(-5, "BUFFERING IS STALLED"), true, "native stall matching ignores case")
    assertEqual(isStartupBufferingStall(-5, "unsupported video codec"), false, "do not retry permanent format errors")
    assertEqual(isStartupBufferingStall(-1, "HTTP 401"), false, "do not retry authentication errors")
    assertEqual(isStartupBufferingStall(-5, "buffering is stalled; HTTP error: 403"), false, "known media refusal overrides stall retry")
    assertEqual(nativePlaybackRefusal("maximum connections reached"), "connection-limit", "explicit connection limit is actionable")
    assertEqual(nativePlaybackRefusal("reader pick stream error:HTTP error:Transfer error: HTTP response code said error response code:(403):403"), "authentication", "recognize native transfer error status")
    assertEqual(nativePlaybackRefusal("HTTP response code said error response code:(429):429"), "rate-limit", "native transfer rate limit is not archive lag")
    assertEqual(instr(1, playbackFailureText(-2, ""), "timed out") > 0, true, "explain timeout")
    lineup = [
        {uuid: "first", name: "First"}
        {uuid: "second", name: "Second"}
        {uuid: "third", name: "Third"}
    ]
    nextChannel = adjacentLiveChannel(lineup, "first", 1)
    assertEqual(nextChannel.channel.uuid, "second", "down selects next channel")
    assertEqual(nextChannel.changed, true, "actual channel change")
    assertEqual(adjacentLiveChannel(lineup, "second", -1).channel.uuid, "first", "up selects previous channel")
    assertEqual(adjacentLiveChannel(lineup, "first", -1).changed, false, "first boundary does not retune")
    assertEqual(adjacentLiveChannel(lineup, "third", 1).changed, false, "last boundary does not wrap")
    assertEqual(adjacentLiveChannel([lineup[0]], "first", 1).changed, false, "single-channel lineup")
    assertEqual(adjacentLiveChannel([], "first", 1), invalid, "empty lineup")
    assertEqual(adjacentLiveChannel(lineup, "removed", 1), invalid, "unknown channel cannot jump to unrelated row")
    assertEqual(adjacentLiveChannel([lineup[0], lineup[2]], "first", 1).channel.uuid, "third", "switching respects filtered lineup")
    assertEqual(adjacentLiveChannel(lineup, nextChannel.channel.uuid, 1).channel.uuid, "third", "rapid presses advance from pending candidate")
    assertEqual(lineup[0].uuid, "first", "selection does not mutate guide content")
    assertEqual(playerChannelDirection("up"), 1, "approved Apple up direction")
    assertEqual(playerChannelDirection("down"), -1, "approved Apple down direction")
    assertEqual(playerChannelDirection("up", "guide"), -1, "configurable guide-order up")
    assertEqual(playerChannelDirection("down", "guide"), 1, "configurable guide-order down")
    assertEqual(playerChannelDirection("options"), 0, "native options is not intercepted")
    assertEqual(playerChannelDirection("back"), 0, "back keeps existing handler")
    audio = playbackTrackChoices([{Track: "a", Name: "English", Language: "eng"}, {Track: "b", Name: "Spanish"}, {Track: "b"}, invalid], "audio", "b")
    assertEqual(audio.count(), 2, "deduplicate valid audio tracks")
    assertEqual(audio[1].title, "[Selected] Spanish", "identify selected audio")
    assertEqual(audio[1].track, "b", "use native audio Track identifier")
    subtitles = playbackTrackChoices([{TrackName: "eia608/1", Description: "English CC"}], "subtitle", "")
    assertEqual(subtitles[0].track, "eia608/1", "use native subtitle TrackName identifier")
    assertEqual(subtitles[0].action, "subtitle", "subtitle selection stays distinct from audio")
    assertEqual(playbackTrackChoices(invalid, "audio", "").count(), 0, "tracks not yet available")
    assertEqual(playbackTrackChoices([{Name: "Missing ID"}], "audio", "").count(), 0, "do not offer unselectable track")
    channels = [{uuid: "a", groupId: "1"}, {uuid: "b", groupId: "2"}, {uuid: "c", groupId: "1"}]
    assertEqual(playerBrowserChannels(channels, "group:1", {}, []).count(), 2, "local group filter")
    assertEqual(playerBrowserChannels(channels, "favorites", {b: true}, [])[0].uuid, "b", "favorites picker")
    recent = playerBrowserChannels(channels, "recent", {}, ["c", "gone", "a"])
    assertEqual(recent.count(), 2, "removed recent hidden")
    assertEqual(recent[0].uuid, "c", "recent order")
    assertEqual(sleepTimerRemaining(0, 100), -1, "no timer")
    assertEqual(sleepTimerRemaining(200, 150), 50, "timer remaining")
    assertEqual(sleepTimerRemaining(200, 200), 0, "timer expiry")
    assertEqual(sleepTimerRemaining(200, 500), 0, "late tick expires once")
    report = nativeStreamDetails({videoFormat: "hevc", audioFormat: "aac", streamInfo: {measuredBitrate: 4500000, streamUrl: "https://user:secret@host/live"}, bufferingStatus: {percentage: 25}}, "secret")
    assertEqual(report.video, "hevc", "native codec preserved")
    assertEqual(report.network, "4500000 bps (at stream selection)", "network estimate is not mislabeled stream bitrate")
    assertEqual(report.buffering, "25%", "native buffering progress")
    assertEqual(instr(1, FormatJson(report), "secret"), 0, "never copy stream URL into diagnostic report")
    assertEqual(nativeStreamDetails(invalid).video, "Unavailable", "no stale codec before current stream is ready")
    assertEqual(nativeStreamDetails({streamInfo: {measuredBitrate: -1}}).network, "Unavailable", "unknown native bitrate is not negative fact")
    assertEqual(nativeStreamDetails({videoFormat: "https://host/key"}).video, "[media URL]", "sanitize unexpected native text")
    stats = nativeStreamDetails({decoderStats: {renderCount: 600, frameDropCount: 0, repeatCount: 0, streamErrorCount: 0, url: "https://secret"}})
    assertEqual(stats.rendered, "600", "measured Roku decoder schema")
    assertEqual(stats.dropped, "0", "zero drops is a valid counter")
    assertEqual(stats.frameRate, "Unavailable", "render count is not encoded frame rate")
    assertEqual(stats.resolution, "Unavailable", "viewport is not decoded dimensions")
    assertEqual(nativeStreamDetails({decoderStats: {renderCount: -1}}).rendered, "Unavailable", "invalid counter rejected")
    server = serverStreamDetails({resolution: "720x480", source_fps: "29.97", video_codec: "h264", url: "https://secret"})
    assertEqual(server.resolution, "720x480", "server dimensions retained as server facts")
    assertEqual(server.frameRate, "29.97 fps", "server fractional frame rate")
    assertEqual(server.doesExist("aspect"), false, "pixel dimensions do not imply display aspect")
    assertEqual(server.doesExist("url"), false, "no provider URL copied")
    assertEqual(sourceVideoStalled({audio: 1.0, video: 1.0}, {audio: 4.0, video: 1.0}), true, "audio-only progress detects frozen picture")
    assertEqual(sourceVideoStalled({audio: 1.0, video: 1.0}, {audio: 4.0, video: 4.0}), false, "healthy source does not restart")
    assertEqual(sourceVideoStalled({audio: 1.0, video: 1.0}, {audio: 1.0, video: 1.0}), false, "paused stream is not frozen-video evidence")
    assertEqual(sourceVideoStalled(invalid, {audio: 4.0, video: 1.0}), false, "unknown metrics cannot trigger recovery")
    assertEqual(sleepTimerLabel(0, 100), "Off", "timer off is explicit")
    assertEqual(sleepTimerLabel(161, 100), "2 min remaining", "timer remaining rounds up")
    print "ALL TESTS PASSED"
end sub

sub assertEqual(actual as dynamic, expected as dynamic, label as string)
    if actual <> expected
        print "FAIL: "; label; " expected="; expected; " actual="; actual
        stop
    end if
end sub
