import { spawnSync } from 'node:child_process';

for (const suite of ['DispatcharrModel', 'GuideModel', 'SceneUi', 'TaskSupport', 'PlaybackModel', 'NowNextModel', 'PreferenceModel', 'CapabilityModel', 'ProgramSearchModel', 'PlayerLifecycle', 'VideoGeometry', 'StreamSourceTask', 'GuideSettingsModel', 'ReminderModel', 'GuideMenu', 'LogoCache', 'VideoInput', 'GuideInput', 'GroupInput', 'PlayerOkHold', 'PlayerRemoteInput', 'GuideRemoteInput', 'StartupRecovery', 'AacStartup', 'CapabilityTask', 'PlayerOptionsInput', 'MetadataCacheModel', 'HttpPolicy', 'GuideTaskCache', 'GuideMappingFallback', 'MappingTask', 'LiveRecovery', 'PlaybackFailure', 'MediaSessionModel', 'VodModel', 'VodState', 'CatchupModel', 'CatchupTask', 'DiagnosticModel', 'OnDemandPlayer', 'ArchiveController', 'VodSeriesLoader', 'NavigationModel', 'DescriptionModel', 'VodDescriptionInput', 'SettingsModel', 'PlayerInfoClock', 'TmdbModel', 'TmdbTask', 'VodShelfTask', 'RemoteMapModel', 'SettingsRail']) {
  const result = spawnSync(process.execPath, [
    'node_modules/brs/bin/cli.js', '--root', 'tests/unit-root',
    'source/DispatcharrModel.brs', 'source/GuideModel.brs', 'source/SceneUi.brs', 'source/TaskSupport.brs',
    'source/PlaybackModel.brs',
    'source/NowNextModel.brs',
    'source/RemoteMapModel.brs', 'source/PreferenceModel.brs',
    'source/CapabilityModel.brs',
    'source/ProgramSearchModel.brs',
    'source/VideoGeometry.brs',
    'source/GuideSettingsModel.brs',
    'source/ReminderModel.brs',
    ...(['TmdbTask', 'VodShelfTask'].includes(suite) ? [] : ['source/MetadataCacheModel.brs']),
    'source/HttpPolicy.brs',
    'source/MediaSessionModel.brs', 'source/VodModel.brs', 'source/VodState.brs', 'source/CatchupModel.brs',
    'source/DiagnosticModel.brs',
    'source/NavigationModel.brs', 'source/DescriptionModel.brs',
    ...(['SettingsModel', 'SettingsRail'].includes(suite) ? ['source/SettingsModel.brs'] : []),
    ...(suite === 'SettingsRail' ? ['components/SettingsRail.brs'] : []),
    ...(suite === 'SettingsModel' ? ['components/SettingsNavigation.brs'] : []),
    ...(['TmdbModel', 'TmdbTask'].includes(suite) ? ['source/TmdbModel.brs'] : []),
    ...(suite === 'TmdbTask' ? ['components/TmdbTask.brs'] : []),
    ...(suite === 'VodShelfTask' ? ['components/VodShelfTask.brs'] : []),
    ...(suite === 'PlayerLifecycle' ? ['components/AerioScene.brs'] : []),
    ...(suite === 'StreamSourceTask' ? ['components/StreamSourceTask.brs'] : []),
    ...(suite === 'GuideMenu' ? ['components/GuideSettings.brs'] : []),
    ...(suite === 'LogoCache' ? ['components/LogoCacheTask.brs'] : []),
    ...(suite === 'VideoInput' ? ['components/AerioVideo.brs'] : []),
    ...(suite === 'GuideInput' ? ['components/GuideView.brs'] : []),
    ...(['GuideInput', 'GuideRemoteInput'].includes(suite) ? ['components/GuideRemoteInput.brs'] : []),
    ...(['PlayerLifecycle', 'PlayerRemoteInput'].includes(suite) ? ['components/PlayerRemoteInput.brs'] : []),
    ...(suite === 'GroupInput' ? ['components/GroupNavigator.brs'] : []),
    ...(['PlayerOkHold', 'PlayerLifecycle'].includes(suite) ? ['components/PlayerOptionsShortcut.brs'] : []),
    ...(['StartupRecovery', 'PlayerLifecycle'].includes(suite) ? ['components/StartupRecovery.brs'] : []),
    ...(suite === 'PlayerLifecycle' ? ['components/LiveRecovery.brs', 'components/PlaybackFailure.brs'] : []),
    ...(suite === 'PlayerLifecycle' ? ['components/MediaNavigation.brs'] : []),
    ...(suite === 'PlayerLifecycle' ? ['components/Diagnostics.brs'] : []),
    ...(suite === 'CatchupTask' ? ['components/CatchupTask.brs'] : []),
    ...(suite === 'OnDemandPlayer' ? ['components/OnDemandPlayer.brs'] : []),
    ...(suite === 'PlayerInfoClock' ? ['components/PlayerInfo.brs'] : []),
    ...(suite === 'ArchiveController' ? ['components/MediaNavigation.brs'] : []),
    ...(suite === 'VodSeriesLoader' ? ['source/VodSeriesLoader.brs'] : []),
    ...(suite === 'VodDescriptionInput' ? ['components/VodView.brs', 'components/VodMetadata.brs'] : []),
    ...(suite === 'LiveRecovery' ? ['components/LiveRecovery.brs'] : []),
    ...(suite === 'PlaybackFailure' ? ['components/PlaybackFailure.brs'] : []),
    ...(['AacStartup', 'PlayerLifecycle'].includes(suite) ? ['components/AacStartup.brs'] : []),
    ...(suite === 'CapabilityTask' ? ['components/CapabilityTask.brs'] : []),
    ...(suite === 'PlayerOptionsInput' ? ['components/PlayerOptions.brs'] : []),
    ...(suite === 'HttpPolicy' ? ['source/DispatcharrHttp.brs'] : []),
    ...(suite === 'GuideTaskCache' ? ['components/GuideTask.brs'] : []),
    ...(suite === 'GuideMappingFallback' ? ['components/GuideCache.brs'] : []),
    ...(suite === 'MappingTask' ? ['components/MappingTask.brs'] : []),
    `tests/${suite}.test.brs`,
  ], { encoding: 'utf8' });
  process.stdout.write(result.stdout ?? '');
  process.stderr.write(result.stderr ?? '');
  if (result.error) throw result.error;
  if (result.status !== 0 || !result.stdout.includes('ALL TESTS PASSED')) process.exit(1);
}
